name: test_udemy_tinder_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:

  cloud_firestore: ^4.12.0
  cupertino_icons: ^1.0.2

  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  firebase_storage: ^11.4.0
  flutter:
    sdk: flutter

  get: ^4.6.6
  image_picker: ^1.0.4

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
