// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYf8HElbRXX1ZMiqhIrt4l6cx7dFh0PDg',
    appId: '1:47719856047:web:408fe9b51d71c644a1615a',
    messagingSenderId: '47719856047',
    projectId: 'test20231003-74bb1',
    authDomain: 'test20231003-74bb1.firebaseapp.com',
    storageBucket: 'test20231003-74bb1.appspot.com',
    measurementId: 'G-8TLHTKLD9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDNQ2hu-eC3X1euxpOoL2l-N7Xax2kQWk',
    appId: '1:47719856047:android:e527398daf32b9fea1615a',
    messagingSenderId: '47719856047',
    projectId: 'test20231003-74bb1',
    storageBucket: 'test20231003-74bb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVy-qhTG06Y2XKKJ6v1Ahzilk-XX8ycM',
    appId: '1:47719856047:ios:156fee293961ebdaa1615a',
    messagingSenderId: '47719856047',
    projectId: 'test20231003-74bb1',
    storageBucket: 'test20231003-74bb1.appspot.com',
    iosClientId: '47719856047-fn1n688lfbk14t9jf4udo34009isjhrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.testMinproInstaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVy-qhTG06Y2XKKJ6v1Ahzilk-XX8ycM',
    appId: '1:47719856047:ios:1acf9948669f3b5ba1615a',
    messagingSenderId: '47719856047',
    projectId: 'test20231003-74bb1',
    storageBucket: 'test20231003-74bb1.appspot.com',
    iosClientId: '47719856047-4d7fngglbsvms43bp1j708h974nnn4g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.testMinproInstaClone.RunnerTests',
  );
}
